### ISSUE TITLE
Sync should not be a dropdown option

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-creator#19]
Sync depends on BQ-syncing. It is not something user would fill

**Comment by Prakhar-commits** [comment]
So we must remove it and what should be its value then, Is it editable for a certain set of users or none of them?

**Comment by suryabulusu** [comment]
we leave it empty -- it gets updated in DB later on. no user can fill it except code (that sets sync to true in db)

**Comment by suryabulusu** [comment]
we leave it empty -- it gets updated in DB later on. no user can fill it except code (that sets sync to true in db). 
we do display sync status once entry is submitted. (in the front page table)
by default, sync status is FALSE
