### ISSUE TITLE
Add basic end to end tests

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-creator#23]
Use cypress or otherwise and write e2e tests. Follow quiz-frontend testing suite for `ci`

Links: 
`ci.yml` - https://github.com/avantifellows/quiz-frontend/blob/main/.github/workflows/ci.yml (see firefox, chrome tests)
`tests` folder - https://github.com/avantifellows/quiz-frontend/tree/main/tests

**Comment by Drish-xD** [comment]
Added E2E Testing in PR #75 .
