### ISSUE TITLE
CI not working

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-creator#38]
Versioning issue? Check

**Comment by soumya-maheshwari** [comment]
Hi @suryabulusu  i want to contribute in this project but i am facing these errors on starting the application

![image](https://github.com/avantifellows/quiz-creator/assets/104725768/4edb742e-6d68-4e1b-9620-a842c90cb0ad)

**Comment by suryabulusu** [comment]
Hello @soumya-maheshwari! Thanks for showing interest. Please refer to this comment: https://github.com/avantifellows/quiz-creator/issues/36#issuecomment-2051290466. Pull the `local_demo` branch instead.

**Comment by yuvrajrathva** [comment]
Hey @suryabulusu, I want to work on this issue. Can you please assign this issue to me.
