### ISSUE TITLE
UI unresponsiveness due to lambda function

### ISSUE THREAD

**Issue by Drish-xD** [avantifellows/quiz-creator#45]
## Description

When a user initiates an action like creating or editing a session, this triggers an AWS Lambda function to process the data and potentially store it in a database. Due to the time it takes the Lambda function to execute, there's a delay before the UI reflects the outcome of the action (success or failure). This delay creates a sense of lag or unresponsiveness in the UI, as the user waits to see the result of their action.

### Expected Behavior

The UI should provide immediate/optimistic feedback upon form submission, indicating that the process is underway. The transition to completion of lambda function and show UI according to the result.

### Current Behavior

The UI appears unresponsive after the form is submitted, leading to a degraded user experience.

**Comment by yuvrajrathva** [comment]
I want to work on this issue. Please assign this issue to me.
