### ISSUE TITLE
Error when Editing Sessions with Character IDs

### ISSUE THREAD

**Issue by yuvrajrathva** [avantifellows/quiz-creator#47]
### Description
When creating a session, alphanumeric characters are accepted in the "CMS TEST ID" (also known as session id) field, allowing successful creation. However, when attempting to edit the same session which have alphanumeric characters in the session ID, an error occurs. To ensure consistency and prevent errors, a validator should be implemented in the "CMS TEST ID" field to disallow input of characters. Screenshots attached for reference.

![image](https://github.com/avantifellows/quiz-creator/assets/102233638/243bb816-1824-47af-9544-28da9c18a92a)
Screen shot of error shown when clicking on edit icon for a session with characters in the session ID.  See to the URI in the screenshot. 

![image](https://github.com/avantifellows/quiz-creator/assets/102233638/ebec1271-8973-4f57-b34d-d3e8d8501758)
Screen shot of page shown when clicking on edit icon for session with only numbers in session ID.

**Expected Behavior:**
- Validator restricts character input in "CMS TEST ID" field.
- Consistent behavior between session creation and editing processes.

**Current Behavior:**
- Session creation allows character input, but editing with characters causes errors.
- Inconsistency in input validation for session ID field.

**Comment by yuvrajrathva** [comment]
It seems that the error may not necessarily be caused by the character input in the "CMS TEST ID" field. The first step is to determine the actual reason behind this error.

**Comment by Drish-xD** [comment]
Fixed
