### ISSUE TITLE
Renaming Readme.md

### ISSUE THREAD

**Issue by Prakhar-commits** [avantifellows/quiz-creator#5]
## Description
This issue is just to test the issue 

## Goals
- [X] Goal 1

## Expected Outcome
This should update the Readme.md

## Implementation Details
Updated the Readme.md

---

### Project
Quiz-Creator

### Organization Name:
Avanti Fellows

### Domain
Education

### Mentor(s)
@suryabulusu  @pritamps 

### Complexity
Low

### Category
Documentation

### Sub Category
Beginner friendly

**Comment by priyanshi2808** [comment]
Hey, can you assign this issue to me

**Comment by aditya0929** [comment]
Hi Can you assign this issue to me ?

**Comment by KRITIKA453** [comment]
hi i am interested in this can you assign this to me?
