### ISSUE TITLE
Issue with Pagination: All Entries Displayed instead of Limit(10) on the single Page.

### ISSUE THREAD

**Issue by SUJALSINGH7473** [avantifellows/quiz-creator#51]
There is an issue with the `pagination` feature in the application. The expected behavior is that each page should display a maximum of `10 entries`, as per the specified limit. However, currently, the application is showing `all entries` on the first page only, disregarding the set limit. This results in a single page containing `all entries`, which can negatively impact the user experience and performance, especially with a large dataset.

**Steps to Reproduce:**

   1. Navigate to the list of entries in the application.
   2. Observe the pagination behavior.

**Expected Behavior:**
      Each page should display a maximum of 10 entries.

**Actual Behavior:**
      All entries are displayed on a single page.

_Before:_
![before pagination](https://github.com/avantifellows/quiz-creator/assets/100035802/f7ed2e09-305e-492b-897a-35886423346b)

_After:_
![after pagination](https://github.com/avantifellows/quiz-creator/assets/100035802/1fd82d6a-b617-458a-9f0e-e2f110c1d44b)

I have resolved this issue in the pr #49

**Comment by Drish-xD** [comment]
Fixed
