### ISSUE TITLE
[BUG] Form Input Not Accepted in Mandatory Textbox, Unable to Proceed to Next Page

### ISSUE THREAD

**Issue by Kaustuv05** [avantifellows/quiz-creator#94]
### Problem Description:
There is a bug in the form where a certain mandatory textbox is not accepting any input, preventing users from submitting the form or proceeding to the next page. This issue occurs even though the textbox should allow input, and it is a required field for form submission.

### Steps to Reproduce:
1. Click on Create Session.
2. Attempt to enter text into the group textbox.
3. Observe that no input is accepted.
4. Try to proceed to the next page or submit the form.
5. Notice that you are unable to continue due to the missing input in the mandatory textbox.

### Expected Behaviour:
- The textbox should accept user input.
- Once the textbox is filled, users should be able to proceed to the next page or submit the form successfully.

### Actual Behavior:
- The textbox does not accept any input.
- Users are prevented from proceeding to the next page due to the incomplete mandatory field.

### Possible Cause:
- The issue may be related to validation rules or the input field's configuration, which prevents it from recognizing user input.

### Proposed Solution:
- Investigate the input validation or event handling associated with the problematic textbox.
- Ensure the textbox is correctly configured to accept user input and validate as expected.
### References:
- Screenshots/Logs: 

https://github.com/user-attachments/assets/77992210-7e5b-42ba-b260-09b9ee6a176c

### Workaround:
No known workaround at this time.

**Comment by suryabulusu** [comment]
hey! thanks for showing interest. 

this isn't a bug. you have to set the environment variable to point to the DB. then, you'd see the dropdown options. the options are explicitly fetched from DB `auth_group` table.
